### ISSUE TITLE
getting `select: Invalid argument` when attempting to run it with phantom js

### ISSUE THREAD

**Issue by Pushplaybang** [DispatchMe/meteor-mocha#18] opened 2017-02-23 15:22 UTC
Hey There

The server side tests run fine, but with the following command I get this error.  My test command is:

```sh
cd app/ && TEST_BROWSER_DRIVER=phantomjs meteor test --once --driver-package dispatch:mocha
```

Any help would be great.  Thanks.

**Comment by Pushplaybang** [comment] 2017-02-23 15:23
note that I have installed phantomjs-prebuilt as described in the readme

**Comment by jaskinn** [comment] 2017-02-24 18:19
I am experiencing this as well.

**Comment by aldeed** [comment] 2017-02-24 18:43
Duplicate of https://github.com/DispatchMe/meteor-mocha-phantomjs/issues/33

Basically you may or may not see this sometimes when running, and it has something to do with memory and/or timing and/or limits on open files. But it's a PhantomJS issue that they most likely won't fix anytime soon, so the best choice is probably to try using one of the other supported browsers.

**Closed by aldeed** 2017-02-24 18:43 UTC
